# Generated by Django 6.0.2 on 2026-02-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100, verbose_name='Test name')),
                ('luotu', models.DateTimeField(auto_now_add=True, verbose_name='Creation datetime')),
            ],
        ),
    ]
