# Generated by Django 6.0.2 on 2026-02-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('population', models.IntegerField()),
                ('region', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('gdp', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
